### PR TITLE
Adding Marlin Build Script and other misc updates

### PR DESCRIPTION
**Pull request by tckb**
Updated the readme and add some basic instructions for flashing

### CODE REVIEW

**Comment by tckb** [comment]
@moonglow  what do you think about the updated instructions? I will add more PRs in the coming days

**Comment by moonglow** [comment]
@tckb 
> what do you think about the updated instructions?

I think instruction related stuff not for main readme, more useful for that is wiki: [WIKI](https://github.com/moonglow/FlashForge_Marlin/wiki)

About SDIO and EEPROM, information can be placed in issue topic or some specific info on wiki page, it not unsupported because it not planing to supports from beginning as example CAMERA interface power pin is not used too ( on new version of motherboard ). Power Loss recovery same thing, it is not unsupported it useless for NX and Dreamer. But of course  it is only my IMHO.

**Comment by moonglow** [comment]
your build script is cool solution, i need to cherry-pick some commits from this request.

**Comment by tckb** [comment]
@moonglow  yes, I am still finalizing the script. I will create a PR for that too

**Comment by tckb** [comment]
> I think instruction related stuff not for main readme, more useful for that is wiki: [WIKI](https://github.com/moonglow/FlashForge_Marlin/wiki)

Yes some of the "How to " could end up in Wiki and this is not still enabled and can't send a PR for  it :P 

>About SDIO and EEPROM, information can be placed in issue topic or some specific info on wiki page,
>it not unsupported because it not planing to supports from beginning as example CAMERA interface power pin is not used too 

exactly, we can add more info in the wiki but, I think this should be something important to be placed along with "what works" and what doesn't work to set the expectations correct. For me, this was a surprise but I understood later on.

**Comment by moonglow** [comment]
> Wiki and this is not still enabled and can't send a PR for it :P

Hm strange, it enabled for me... i will check thanx

> I think this should be something important 
> what doesn't work

Sorry, but i can't relate it to this section, this mean if some does not works it will works in future, but it does not works ever, because it must "not works".

**Comment by tckb** [comment]
>because it must "not works".

I think I understand what you mean. I can rename it to "Unsupported"  this is what you mean.

**Comment by moonglow** [comment]
this is not "unsupported" this is just nothing and whats why it does not appear in readme. If you name it "unsupported" someone will open ISSUE:

Need to add support for internal SD card and external EEPROM chip :)

you can leave it as is, i think it is not a big problem to have description you want to have, the biggest problem already solved and firmware works on our printers.

**Comment by tckb** [comment]
>Need to add support for internal SD card and external EEPROM chip :)

For this, this is why I added a comment to describe why this is decided and this is not uncommon.  Didn't you mention Marlin doesn't support two SD cards? 

>If you name it "unsupported" someone will open ISSUE:

Haha, that's clearly wouldn't be supported :P


>you can leave it as is, i think it is not a big problem to have description you want to have

once you enable the WIKI and I can access it I will move this "How to" section to wiki and will add a section of build instructions too.  I am setting up a CI on my fork (FYI) for generating builds

**Comment by moonglow** [comment]
> Didn't you mention Marlin doesn't support two SD cards?

i think most of users for such repo is not a developers, another thing not that all developers know about it too :)

> I am setting up a CI on my fork (FYI) for generating builds

wow thats is really cool update !

**Comment by tckb** [comment]
@moonglow  here's the automated release for my fork, feel free to test
https://github.com/tckb/FlashForge_Marlin/releases

**Comment by moonglow** [comment]
Very nice solution! I love it ! i will test it a little and merge to main repo !

**Comment by tckb** [comment]
@moonglow  I use `fork-main` for all the changes I'd like to do. This branch differs from `main`  The github workflow is configured there.  You can pick stuff up there too.

**Comment by moonglow** [comment]
> You can pick stuff up there too.

for such solution i ready to grab it all :) 

p.s: btw copy of config in build folder is nice idea, but we need also `Configuration_adv_<machine_name>.h` because it has some changes for each machine, also a little thing for build script, script do not comment `FF_DREAMER_NX_MACHINE` if we build for Inventor or Dreamer, but all other things is just WOW...

**Comment by tckb** [comment]
>need also Configuration_adv_<machine_name>.h because it has some changes for each machine, also a little thing for build script, script do not comment FF_DREAMER_NX_MACHINE

Yes, there are certain things that  might change for different machines, also in configuration.h. I have some plan to do it, I will have proper changes in place to test them later on. keep a watch ;)


>also a little thing for build script, script do not comment FF_DREAMER_NX_MACHINE

the script uncomments the machine specific configuration, builds the firmware and restores the original configuration. You will find the updated config in BUILD folder

**Comment by moonglow** [comment]
> the updated config in BUILD folder

yep i mean updated config, as example:

Dreamer:
```
#define FF_FLASHAIR_FIX
//#define FF_INVENTOR_MACHINE
#define FF_DREAMER_MACHINE
#define FF_DREAMER_NX_MACHINE
//#define FF_EXTRUDER_SWAP
```

Inventor:
```
#define FF_FLASHAIR_FIX
#define FF_INVENTOR_MACHINE
//#define FF_DREAMER_MACHINE
#define FF_DREAMER_NX_MACHINE
//#define FF_EXTRUDER_SWAP
```

NX:
```
#define FF_FLASHAIR_FIX
//#define FF_INVENTOR_MACHINE
//#define FF_DREAMER_MACHINE
#define FF_DREAMER_NX_MACHINE
//#define FF_EXTRUDER_SWAP
```


`FF_DREAMER_NX_MACHINE` - is always uncomment

**Comment by tckb** [comment]
> > the updated config in BUILD folder
> 
> yep i mean updated config, as example:
> 
> Dreamer:
> 
> ```
> #define FF_FLASHAIR_FIX
> //#define FF_INVENTOR_MACHINE
> #define FF_DREAMER_MACHINE
> #define FF_DREAMER_NX_MACHINE
> //#define FF_EXTRUDER_SWAP
> ```
> 
> Inventor:
> 
> ```
> #define FF_FLASHAIR_FIX
> #define FF_INVENTOR_MACHINE
> //#define FF_DREAMER_MACHINE
> #define FF_DREAMER_NX_MACHINE
> //#define FF_EXTRUDER_SWAP
> ```
> 
> NX:
> 
> ```
> #define FF_FLASHAIR_FIX
> //#define FF_INVENTOR_MACHINE
> //#define FF_DREAMER_MACHINE
> #define FF_DREAMER_NX_MACHINE
> //#define FF_EXTRUDER_SWAP
> ```
> 
> `FF_DREAMER_NX_MACHINE` - is always uncomment

Oh that is a bug!  interesting, I didn't such behavior. What is in "configuration.h"

**Comment by moonglow** [comment]
while build in process it changes as it was in previous message, after build was finished it comes to default state

**Comment by tckb** [comment]
works as expected on mac, I'd probably blame it on `sed` portability.  I will replace it with more portable solution ;)

**Comment by tckb** [comment]
@moonglow  can you try it now? I've made some changes

**Comment by moonglow** [comment]
Perl ?:) you know too much dev tools hehe

I think your previous version is better we have only ONE config and change only defines inside it, now you add same configs for each machine with only few defines changed ? and if we change something we need to manual change it in other place too. Before you modify on the fly config and build with it also you put actual config to BUILD directory and it is very useful for users who can check it, but now it is less useful i think, i will try to fix your previous version if you want because it is really cool

**Comment by tckb** [comment]
@moonglow  Yes, it was too finicky to do regexs  and doesn't work always to be platform independent. `sed`  flags are not portable enough to be the same in mac and linux. we need to detect the platforms in build script and switch, thats messy.  This is why I used `perl` which works ;) 

For machine specific configs, yes for now this is just one liner difference but this will not remain the same. There's always machine specific changes , and at one point you do not know what is the current config for a machine. This is generated on the fly and in the BUILD but when you have multiple releases you wouldn't know, one way to mitigate that is to have this`#ifdef` switches -- I find it extremely  inconvenient  to maintain. This is why I chose to have a clean different config. 

Yes, you need to duplicate common changes -- _for now_  I will rethink it later on

**Comment by moonglow** [comment]
Hm... you change your road map really fast ^_^ I will try to combine something from that, but you can use not a `sed`, a something like that:

include this line to main config:
`#include "Machine.h"`

and generate this file as you wish run-time, without problems and regexp i think it be more clean solution, another thing if we use different settings from machine to machine we can put it to our generated Machine.h ,because 80% of other settings will be same in most cases.

**Comment by tckb** [comment]
> Hm... you change your road map really fast ^_^

failfast & iterate that's the motto :P ha currently I don't have a roadmap yet, I am still streamlining the CI process and automate the build process. setting up change logs, building machine specific builds, releases etc. 

> include this line to main config:
> `#include "Machine.h"`
>and generate this file as you wish run-time, without problems and regexp i think it be more clean solution,

Thanks for the hint! that seems to be a good solution, I don't do c/c++ a lot .. I am still figuring out the best way possible. 


>  another thing if we use different settings from machine to machine we can put it to our generated Machine.h ,
>because 80% of other settings will be same in most cases.

yes!

**Comment by tckb** [comment]
@moonglow  thanks for the good tip! I managed build it using only required: 

https://github.com/tckb/FlashForge_Marlin/tree/fork_main/configs

the common config is here: https://github.com/tckb/FlashForge_Marlin/blob/06ded890703e75634488b678166202fc14f6c5c3/Marlin/Marlin/Configuration.h#L23

**Comment by tckb** [comment]
@moonglow  are you still interested this PR?  if you need any specific parts of the fork, please check [`fork_main`](https://github.com/tckb/FlashForge_Marlin/tree/fork_main/configs)  instead of `main`

**Comment by moonglow** [comment]
@tckb looks like your goes really far from my understanding of build system and it looks very overengineered  for me ^_^. I prefer more easy to understand solution and my main goal it is firmware, but you did a great build system for it with CI and so on, looks very professional, but i can't accept such solution as is. I think parallel solution is good too and i watching :eyes: it from time to time.

**Comment by tckb** [comment]
>looks very overengineered for me ^_^.

Haha, also less maintenance  and more work ;) 

>main goal it is firmware

yes I looked at the changes you did, there seems to be a good bit of internal changes, I'm trying  to figure it out bit by bit ;) Have some changes in mind, will add those later. 

>I think parallel solution is good too
💯 

> but i can't accept such solution as is. 
> i watching 👀 it from time to time.

sure thing, I will close this PR and feel free to pull any changes you need.  I saw your latest changes, will pull some of them (the Toshiba SD card changes). got my 👁️‍🗨️  👁️‍🗨️  on your branch too :P

**Pull request closed without merging**
