### PR TITLE
sdio_stm32duino.cpp has been removed from upstream Marlin, make DIGIPOT settings more flexible

### PR DESCRIPTION
**Pull request by Mrnt**
- sdio_stm32duino.cpp has been removed from upstream Marlin
- make DIGIPOT settings more flexible and compatible with upstream Marlin.

### CODE REVIEW

**Comment by moonglow** [comment]
Hi @Mrnt !

Hm... did your sure about SDIO driver ? [HERE](https://github.com/moonglow/FlashForge_Marlin/blob/marlin_2.0.x/Marlin/Marlin/src/HAL/STM32/Sd2Card_sdio_stm32duino.cpp)

About `DIGIPOT` yeap i like that idea i think we need to make pull request to  official Marlin repo with that feature, because it useful for other users too. But defines needs to make both uppercase as it used in other marlin configs !

**Comment by Mrnt** [comment]
> Hm... did your sure about SDIO driver ? [HERE](https://github.com/moonglow/FlashForge_Marlin/blob/marlin_2.0.x/Marlin/Marlin/src/HAL/STM32/Sd2Card_sdio_stm32duino.cpp)

If you enable SDIO_SUPPORT you will get a build error because of multiple definitions of SDIO functions. If you look at the current Master branch of [Marlin](https://github.com/MarlinFirmware/Marlin/tree/2.0.x/Marlin/src/HAL/STM32) they have removed Sd2Card_sdio_stm32duino.cpp, and added a replacement SDIO driver Jan 8:
https://github.com/MarlinFirmware/Marlin/commits/2.0.x/Marlin/src/HAL/STM32/sdio.cpp

>About DIGIPOT yeap i like that idea i think we need to make pull request to official Marlin repo with that feature, because it useful for other users too. But defines needs to make both uppercase as it used in other marlin configs !

I was surprised Marlin did not do that already. Seems unlikely that every driver would have the same exact circuit. They use mixed case in their [file](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/Marlin/src/feature/digipot/digipot_mcp4018.cpp). I will have a go at making a pull request on the official repo.

**Comment by Mrnt** [comment]
BTW, thank you for doing this project. I had made an OctoPrint plugin for these printers but even though it works, it is not reliable - the FlashForge firmware does not seem to behave in a consistent, predictable fashion. And it is of course, an opaque, black box of closed source.

**Comment by moonglow** [comment]
>you will get a build error because of multiple definitions of SDIO functions.

Ah... that's my fault sorry i forgot. Thanks for your tips. Looks like something goes wrong when i apply previous merge ^_^ 

>I was surprised Marlin did not do that already.

Totally agree 

> They use mixed case in their

Yep , but it looks ugly :)

>BTW, thank you for doing this project. 

You are welcome i hope it be useful for many users and bring new life to their printers :+1: 

>black box of closed source.

Their base firmware is port of Sailfish with GUI from Segger ,but they did not wants to open their modifications and that's sad, yep.... who needs outdated or feature less firmware ...

**Pull request merged**
